/**
 * File: cdk/lib/frontend-stack.ts
 * Description: Deploys the React Frontend.
 * Resources:
 * 1. S3 Bucket: Stores the built HTML/JS/CSS files.
 * 2. CloudFront: CDN to serve content globally via HTTPS.
 * 3. S3Deployment: Uploads the local 'frontend/dist' folder to S3.
 */

import * as cdk from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as path from 'path';
import { Construct } from 'constructs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export class FrontendStack extends cdk.Stack {
    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        // 1. S3 Bucket (Website Host)
        const websiteBucket = new s3.Bucket(this, 'NexusMarineFrontendBucket', {
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            autoDeleteObjects: true,
            blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL, // Security: Access only via CloudFront
        });

        // 2. CloudFront Distribution
        const distribution = new cloudfront.Distribution(this, 'NexusMarineDistribution', {
            defaultBehavior: {
                origin: new origins.S3Origin(websiteBucket),
                viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
            },
            defaultRootObject: 'index.html',
            errorResponses: [
                {
                    httpStatus: 404,
                    responseHttpStatus: 200,
                    responsePagePath: '/index.html', // Essential for React Router (SPA)
                }
            ]
        });

        // 3. Deploy Assets
        // This takes the 'dist' folder generated by 'npm run build' and uploads it.
        new s3deploy.BucketDeployment(this, 'DeployWebsite', {
            sources: [s3deploy.Source.asset(path.join(__dirname, '../../frontend/dist'))],
            destinationBucket: websiteBucket,
            distribution, // Invalidate CloudFront cache after deployment
            distributionPaths: ['/*'],
        });

        new cdk.CfnOutput(this, 'FrontendUrl', {
            value: distribution.distributionDomainName,
            description: 'URL of the deployed React App',
        });
    }
}